### ISSUE TITLE
Failed to init libevdev (Bad file descriptor)

### ISSUE THREAD

**Issue by vanillasoap** [zcqsntr/retro_matrix#3]
Hey, I've been trying to get this to work without success. I can't get past the start menu as no keys are recognized, I've tried all keys on my keyboard and a ps4 controller.

I'm on Manjaro running gnome. I did actually try running it in Ubuntu, but got the same outcome.

There seems to be an issue with libevdev, I'm not too familiar with it though, and it seems hard to find any answer upon searching.

Any clues?

```
~/git/retro_matrix master*
❯ ./run_retro_matrix --led-slowdown-gpio=4 --led-gpio-mapping=adafruit-hat
Must run as root to be able to access /dev/mem
Prepend 'sudo' to the command

~/git/retro_matrix master*
❯ sudo ./run_retro_matrix --led-slowdown-gpio=4 --led-gpio-mapping=adafruit-hat
3432
3
Failed to init libevdev (Bad file descriptor)
"/dev/input/event5"-1-9
Failed to init libevdev (Bad file descriptor)
"/dev/input/event4"-1-9
Failed to init libevdev (Bad file descriptor)
"/dev/input/event3"-1-9
Failed to init libevdev (Bad file descriptor)
"/dev/input/event2"-1-9
Failed to init libevdev (Bad file descriptor)
"/dev/input/event1"-1-9
Failed to init libevdev (Bad file descriptor)
"/dev/input/event0"-1-9
```

Edit: it does work in raspbian. I'm guessing there was some conflict with libinput in manjaro.

**Comment by zcqsntr** [comment]
This makes sense. It looks like it can't find the files to read inputs from, I assume they might be in a different place on a different OS

**Comment by sub-zerohm** [comment]
I know the issue was closed, and this is a total necro bump, but the author says not to use sudo and this is why.  I'm having the same issue.  It requires sudo to use the pwm mode but it cannot find it unless you run it as the user profile.  It says it works in raspbian but that's the one I'm using and I'm getting this issue.... Did you not run sudo when you ran it in raspbian?  It seems like it's looking for libevdev under a user profile, or a particular location.  I'm going to see if I can chown the libevdev folder inside the package's root directory or something similar?  Lib EV Dev gets cloned in the instructions by the user and it gets configured and installed by the user, which would explain why root doesn't have access to it.... So another possibility is running setup.sh as sudo.  And if that doesn't work I'm going to try programming the app with SDL inputs.  Pwm is almost required for these 64x64 panels to remove the flicker which I'm still seeing without the PWM mode.

Another alternative is to actually just chain two 64x32 panels together, And give the appropriate arguments (refer to the original library linked but I believe it is parallel and serpentine)  They don't require the pwm and This library can figure out that logic with the arguments.  The pitch is also slightly bigger on those panels so it will give you a bigger screen overall, it will just take a little bit more to build the frame

**Comment by sub-zerohm** [comment]
So I tried all of this besides re-coding the inputs.  Nothing working besides trying to chain 2 together, but I still get flicker on Tetris when you have a full screen of pieces.  The other games work flawlessly.  I'd like to try and code a breakout clone and add it to this, or gradius

![Image](https://github.com/user-attachments/assets/3ad9cc9a-6fbb-4120-93e8-bcc5d34cabcd)
![Image](https://github.com/user-attachments/assets/65d8840d-477d-47b6-8d13-851e469babee)
